openapi: 3.1.0
info:
  title: Rule-Based Turkish-English Translator
  version: 1.0.0
servers:
  - url: https://translate-api-o1of.onrender.com
paths:
  /translate:
    post:
      operationId: strictTranslate
      summary: Translate Turkish academic text into English under strict rules
      description: >
        Translates Turkish academic or official texts to English under strict rules.
        The translation must NOT contain em dash (—), en dash (–), or alter any numeric values (such as footnote numbers).
        Plain digit footnote numbers must be preserved. Violations will return a 422 error.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Turkish academic or official text
              required:
                - text
      responses:
        '200':
          description: Clean translated English text
          content:
            text/plain:
              schema:
                type: string
        '422':
          description: Violation of translation rules
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Translation stopped due to instruction violation.

